### ISSUE TITLE
how about magento ? 

### ISSUE THREAD

**Issue by zhibinwang** [carmum/schedule#2]
try chinese version http://www.360magento.net/magento-chinese-v01/
is it suitable for us to do 2rd dev ?

**Comment by dabing1022** [comment]
# 开源电子商务系统 Magento

## 特点

-  开源PHP电子商务系统
-  强大的商品属性组合
-  购物车价格规则
-  灵活的模板系统，网上有大量的模板可用
-  多网店系统
-  完善的插件体系
-  安全加密
-  企业应用集成
-  容易整合
-  新颖的功能
-  专业与社群支援
-  完整的扩充性

## 功能点
1. 网站管理
2. 促销和工具
3. 国际化支持
4. SEO搜索引擎优化
5. 结账方式
6. 运输快递
7. 支付方式
8. 客户服务
9. 用户帐户
10. 目录管理
11. 目录浏览
12. 产品展示
13. 分析和报表

## 使用案例

-  [威锋商城](http://www.fengbuy.com/)
-  [球衫堂商店](http://shop.kitstown.com/)
-  [Angry Birds Online Store愤怒的小鸟的在线商城](http://shop.angrybirds.com/)
-  [Samsung Mobile Shop](http://mobileshop.samsung.fr/)
-  [Lenovo outlet](http://outlet.lenovo.com/)

**Comment by zhibinwang** [comment]
@dabing1022  How about http://www.360magento.net/magento-chinese-v01/
