### ISSUE TITLE
Framework or not ?  rails or  php ? 

### ISSUE THREAD

**Issue by zhibinwang** [carmum/schedule#3]
###Framework or not  ?
- I think what we need is basic mvc framework without business logic.
- Using  framework such as spree/magento  (it is has e-commerce logic inside) , we need do some add/remove/modify lots code inside it , so first we need understand its code, that's hard. Maybe it has its own bugs inside , hard for us to fix them. 
- Using basic MVC framework without any logic inside , we do not need care about our architecture and can focus on our logic. With common framework like Rails , lots of existing module can be used (https://rubygems.org). 

http://www.asksomegeeks.com/posts/online-information-for-geeks/ruby-on-rails-vs-php.html 
http://www.comentum.com/ruby-on-rails-vs-php-comparison.html 
http://www.learncomputer.com/php-vs-ruby-on-rails/ 

I prefer Rails: 
-  I used rails in 2 apps. 
- It is a MVC architecture , has its own http server ( easy to replace with apache2 or nginx) , has its own database ( easy to replace with mysql or others). 

Done, we are going to use Rails. 

Next is prepare requirement & design& code.

**Comment by dabing1022** [comment]
Ok.
